Fixed custom converter in mapping attribute
dkorolev1/SP2016.Repository pull request #7
Opened 2019-02-27 12:00 UTC by vloput

2019-02-28 09:11 UTC, dkorolev1 commented on SP2016.Repository/Converters/Common/JsonConverter.cs
> +            return JsonConvert.DeserializeObject<T>(fieldValue as string);
Мне кажется, что этот класс не должен быть шаблонным. Есдинственно место где ты ты используешь параметр типа это здесь `return JsonConvert.DeserializeObject<T>(fieldValue as string);`

Но у тебя приходит параметр `propertyInfo`, из которого ты сможешь очень просто получить тип своего свойства.

2019-02-28 09:12 UTC, dkorolev1 commented on SP2016.Repository.Tests/Data/Users/UserEntity.cs
> +        public Dictionary<string, Seniority> Skills { get; set; }
Не совсем понял зачем в данном конкретном случае использовать Dictionary. Как минимум, можно просто использовать массив, в случае необходимости ты всегда можешь просто сделать ToDictionary, но в большинстве случаев в этом не будет необходимости. Ну и вот эти свойства (string, Seniority) - мне кажется, что здесь лучше всего было бы завернуть эти поля в какой то класс. Кстати, в C# 8 будет новый крутой синтаксис для создания подобных классов контейнеров. [можешь тут читануть если будет время](https://blog.cdemi.io/whats-coming-in-c-8-0-records/).

2019-02-28 09:13 UTC, dkorolev1 commented on SP2016.Repository/Attributes/FieldMappingAttribute.cs
>          {
Давай будем здесь выбрасывать Exception, если Type не унавледован от FieldConverter. Обсуждали по телефону.

2019-02-28 09:15 UTC, dkorolov1 requested changes
В целом все круто. Оставил там пару комментов, в принципе там незначительные изменения думаю можно было бы сделать. Глянь как будет время. Спасибо.

2019-03-01 07:30 UTC, vloput commented on SP2016.Repository/Converters/Common/JsonConverter.cs
> +            return JsonConvert.DeserializeObject<T>(fieldValue as string);
Согласен, поправил метод.

2019-03-01 07:32 UTC, vloput commented on SP2016.Repository.Tests/Data/Users/UserEntity.cs
> +        public Dictionary<string, Seniority> Skills { get; set; }
Здесь была задача протестировать JsonConverter. Использовал первый тип, который пришёл в голову.
Согласен, лучше вынести Skill в отдельный класс. Поправил.

2019-03-01 07:32 UTC, vloput commented on SP2016.Repository/Attributes/FieldMappingAttribute.cs
>          {
Согласен.

2019-03-01 07:33 UTC, vloput commented
Внёс правки, отправил изменения.

2019-03-01 08:57 UTC, dkorolev1 commented on SP2016.Repository/Mapping/FieldMapper.cs
> +            if (mapping.Converter != null && !mapping.Converter.IsSubclassOf(typeof(FieldConverter)))
Мне не очень нравится располагать эту проверку здесь. Возможно, её также не очень логично располагать в FieldMappingAttribute с зрения того, что по сути FieldMappingAttribute является просто классом контейнером и если выбрасывать там исключения, которые относятся к бизнес логике это будет немного странно. А здесь не очень, потому мне кажется что название метода и его цели не очень коррелируются с этой проверкой и исключением. Ну и еще, насколько я понимаю, это исключение вылетит когда ты попытаешься использовать репозиторий, но лучше было бы если оно вылетало непосредственно при инициализации, как мне кажется.

2019-03-01 08:58 UTC, dkorolov1 approved these changes
approved.

2019-03-01 09:03 UTC, merged